### ISSUE TITLE
Bypass nag for imageVersion if the project is configured for RP

### ISSUE THREAD

**Issue by huntc** [sbt/sbt-conductr#112]
If there's a `project/typesafe.properties` file present and `image` is `conductr/conductr-dev` then set the `imageVersion` to the latest version available (`1.0.11`).

**Comment by huntc** [comment]
@edwardcallahan Don't worry about this one - I'll assign to Markus  as I need it before you start work.

**Comment by markusjura** [comment]
Fixed with PR https://github.com/typesafehub/sbt-conductr-sandbox/pull/35.
