### ISSUE TITLE
Improve error messages for logs, events, services, info

### ISSUE THREAD

**Issue by markusjura** [sbt/sbt-conductr#114]
The error message for the following conduct commands need to be improved:
- logs
- events
- services
- info

So far these commands are timing out after 5 seconds if ConductR does not respond, e.g. if ConductR has not been started. Especially as a first user experience this is particularly bad. Instead the failure case should return with a concrete error message.

This issue should be fixed while implementing the new HTTP library for `sbt-conductr`.

**Comment by markusjura** [comment]
To be more concrete, the commands should:
- Try to fail fast. If control server is not set the current command should set the control server
  - If setting the control server fails it should display an error message that docker has not been started (ip address is not reachable)
- In all cases it should return the most concrete error message

@huntc: WDYT?

**Comment by huntc** [comment]
Sounds good

**Comment by markusjura** [comment]
Addressed by PR https://github.com/sbt/sbt-conductr/pull/124.
