### ISSUE TITLE
Pick configuration at load time, probably also define how ConductR works with "environments"

### ISSUE THREAD

**Issue by ktoso** [sbt/sbt-conductr#48]
It's currently rather confusing how to "load bundle with my config", the nearest thing to it docs wise is the section on shazar here: http://typesafehub.github.io/typesafe-conductr/intro/Quickstart.html

One use case is: Apps sometimes have modes, or demo-apps we prepare as activator templates often have `frontend` and `backend` roles (including reactive maps, akkamazing etc). So still while developing the app I want to:
* start bundleX with `backend` configuration on `backend` nodes
* start bundleX with `frontend` configuration on `frontend` nodes.

This is different than ops overlaying their configuration (with for example prod keys / urls etc). I have the full config in my development sources, and it's committed. I'd advocate for supporting "environment configuration", like in chef: https://docs.chef.io/environments.html so we'd have `src/resources/conductr/env.conf` and `src/resources/conductr/end_frontend.conf` etc. 

* I want to be able to pick which env config to shazar and include when loading. It would be nice to have conventions in place, so not every team has it completely differently. Thus the above proposal with `conductr/env[name].conf` (or it could be `.sh`). I'd personally like it to be usable like so: `load -E frontend mybundle`.
* I want to have this name exposed as env variable, so my app can act upon it. We do have activator templates that notice "oh, I'm a frontend node now, okey!".

**Comment by ktoso** [comment]
Here is a link which should hopefully explain my perspective and what I'm missing here currently:
* https://www.digitalocean.com/community/tutorials/how-to-use-roles-and-environments-in-chef-to-control-server-configurations

**Comment by dsugden** [comment]
proposed design:

Folder convention:

    source/main/configuration/<confFolder>

confFolder name represents the configuration 

In this folder would be an (optional) bundle.conf and runtimeconfig.sh

Introduce a separate step (and associated mapping/task):

    config:dist

that shazar's this config

user would tab complete for bundle, SPACE then tab complete for configuration.

**Comment by huntc** [comment]
Thanks @dsugden - spot on per our conversation yesterday. All but the last sentence is `sbt-bundle` of course.

**Comment by huntc** [comment]
One major component of this use-case is now solved given https://github.com/sbt/sbt-bundle/pull/47

The remainder is to support tab completion on the configuration parameter using the result of the last `configuration:dist` task. @dsugden - may I stretch our new relationship and ask this of you? :-)

**Comment by dsugden** [comment]
Love it! I'm all over this.

**Comment by dsugden** [comment]
@huntc  I'll need someone to publish sbt-bundle 0.23.0 to bintray before I can merge this PR, as the config:dist task isn't in 0.22.0
For now I can publish-local

**Comment by huntc** [comment]
`0.23.0` is now released.

**Comment by dsugden** [comment]
cool, PR is up
