### ISSUE TITLE
Enhance scripted test

### ISSUE THREAD

**Issue by dsugden** [sbt/sbt-conductr#67]
As described in http://eed3si9n.com/testing-sbt-plugins , which seem to still be up to date for 0.13.x

1. Add the scripted plugin 
2. Write a test that validates > controlServer <url> actually changes State

Unless I'm mistaken, I think this requires the dev being able to publish locally. I wasn't success in my initial attempts at this, will update this issue with more info

**Comment by huntc** [comment]
There's a scripted test already there. It just needs a task in its build.sbt to validate the setting. :-)
