### ISSUE TITLE
Change substask "start" to "run"

### ISSUE THREAD

**Issue by dsugden** [sbt/sbt-conductr#68]
"Upload completed. Use 'startBundle 858d8e0c3215ece38318355d17f25766' to start."

should be:

"Upload completed. Use 'conduct start 858d8e0c3215ece38318355d17f25766' to start."

**Comment by hseeberger** [comment]
Good catch! PR?

**Comment by dsugden** [comment]
Re-purposing this issue.

Change all uses of the word "start" to "run" wrt the substask

I was thinking of just renaming "startSubtask" to "runSubstask" and changing the strings output to user accordingly.

the word "start" is pretty ubiquitous in code... change it everywhere? thoughts?

**Comment by huntc** [comment]
SGTM - it is pretty much what we did in the ConductR code base itself. Thanks.
