### ISSUE TITLE
Enhance scripted tests to include all substasks

### ISSUE THREAD

**Issue by dsugden** [sbt/sbt-conductr#74]
Add scripted tests for all subtasks:
load,run,stop,unload.

This could be enabled with a (task? test plugin?) in the sbt-test build.sbt that mocks a conductr server.

in test:

> controlServer 127.0.0.1:9005

> startConductRMock 127.0.0.1:9005

> conduct load file:///......

> checkLoad <bundle id>

...

**Comment by markusjura** [comment]
Will be fixed together with issue #110.

**Comment by markusjura** [comment]
Solved by https://github.com/sbt/sbt-conductr/pull/131.
