### ISSUE TITLE
Change organization to com.typesafe.sbt

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-conductr#88]
For all of our public sbt plugins we are using com.typesafe.sbt.

**Comment by huntc** [comment]
Unsure whether I agree. We can change of course, but my original motivation was to name it such because the plugin has an exclusive relationship to ConductR, and is not a general sbt plugin.

WDYT @jsuereth ?

**Comment by markusjura** [comment]
@huntc: What's the status here?

**Comment by huntc** [comment]
Our plugins have little utility beyond ConductR, so I believe that they should be retained with the namespace that they have. Closing out.
