### ISSUE TITLE
Complete events and logs commands when format is settled

### ISSUE THREAD

**Issue by 2m** [sbt/sbt-conductr#93]
Continuation of #92

**Comment by markusjura** [comment]
Addressed with PR #104.

**Comment by typesafe-tools** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8meDbFgO&#x2F;113-sbt-conductr-needs-to-enable-the-logs-and-events-command"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> sbt-conductr needs to enable the logs and events command</a>
